Repository wisemen-digital/eslint-config-vue, pull requests merged in 2024-05, with the labels that each got.

#13 [Feature] Add parens rule. Add extension rule. Update changelog.
  CHANGELOG.md
  eslint.config.js
  package.json
  pnpm-lock.yaml
  src/base.js
  src/compatLint.js
Labels: 📃 S PR, ✨ feature

#12 feat: ordening rules for routing
  CHANGELOG.md
  src/perfectionist.js
Labels: 📃 XS PR, ✨ feature

#14 feat: updated eslint to 9.3
  CHANGELOG.md
  eslint.config.js
  package.json
  pnpm-lock.yaml
  src/compatLint.js
  src/perfectionist.js
  src/tailwind.js
Labels: 📃 XL PR, ✨ feature

#15 [Feature] routes ordening
  CHANGELOG.md
  package.json
  src/perfectionist.js
Labels: 📃 XS PR, ✨ feature
